document
  .getElementById("translate-btn")
  .addEventListener("click", translateText);
document.getElementById("mic-btn").addEventListener("click", showModal);
document.getElementById("speak-btn").addEventListener("click", speakOutput);
document.getElementById("closeModal").addEventListener("click", closeModal);

function translateText() {
  const fromLang = document.getElementById("from-language").value;
  const toLang = document.getElementById("to-language").value;
  const inputText = document.getElementById("input-text").value.toLowerCase(); // Normalize input

  let translatedText = "";

  // Updated translations with Hindi (hi) added
  const translations = {
    // Existing translations
    hello: {
      en: "Hello",
      fr: "Bonjour",
      es: "Hola",
      de: "Hallo",
      hi: "नमस्ते",
    },
    goodbye: {
      en: "Goodbye",
      fr: "Au revoir",
      es: "Adiós",
      de: "Auf Wiedersehen",
      hi: "अलविदा",
    },
    "thank you": {
      en: "Thank you",
      fr: "Merci",
      es: "Gracias",
      de: "Danke",
      hi: "धन्यवाद",
    },
    yes: {
      en: "Yes",
      fr: "Oui",
      es: "Sí",
      de: "Ja",
      hi: "हाँ",
    },
    no: {
      en: "No",
      fr: "Non",
      es: "No",
      de: "Nein",
      hi: "नहीं",
    },
    // Additional 20 translations
    please: {
      en: "Please",
      fr: "S'il vous plaît",
      es: "Por favor",
      de: "Bitte",
      hi: "कृपया",
    },
    sorry: {
      en: "Sorry",
      fr: "Désolé",
      es: "Lo siento",
      de: "Entschuldigung",
      hi: "माफ़ करना",
    },
    "excuse me": {
      en: "Excuse me",
      fr: "Excusez-moi",
      es: "Perdón",
      de: "Entschuldigen Sie",
      hi: "मुझे माफ करें",
    },
    "how are you": {
      en: "How are you?",
      fr: "Comment ça va?",
      es: "¿Cómo estás?",
      de: "Wie geht's?",
      hi: "आप कैसे हैं?",
    },
    "i am fine": {
      en: "I am fine",
      fr: "Je vais bien",
      es: "Estoy bien",
      de: "Mir geht's gut",
      hi: "मैं ठीक हूँ",
    },
    "see you soon": {
      en: "See you soon",
      fr: "À bientôt",
      es: "Hasta pronto",
      de: "Bis bald",
      hi: "फिर मिलेंगे",
    },
    "where is the exit": {
      en: "Where is the exit?",
      fr: "Où est la sortie?",
      es: "¿Dónde está la salida?",
      de: "Wo ist der Ausgang?",
      hi: "निकास कहाँ है?",
    },
    "i am learning": {
      en: "I am learning",
      fr: "J'apprends",
      es: "Estoy aprendiendo",
      de: "Ich lerne",
      hi: "मैं सीख रहा हूँ",
    },
    "let's go": {
      en: "Let's go",
      fr: "Allons-y",
      es: "Vamos",
      de: "Los geht's",
      hi: "चलो",
    },
    "what is your job": {
      en: "What is your job?",
      fr: "Quel est votre travail?",
      es: "¿Cuál es tu trabajo?",
      de: "Was ist dein Beruf?",
      hi: "आपका काम क्या है?",
    },
    "i need help": {
      en: "I need help",
      fr: "J'ai besoin d'aide",
      es: "Necesito ayuda",
      de: "Ich brauche Hilfe",
      hi: "मुझे मदद चाहिए",
    },
    "i don't know": {
      en: "I don't know",
      fr: "Je ne sais pas",
      es: "No sé",
      de: "Ich weiß nicht",
      hi: "मुझे नहीं पता",
    },
    "do you like it": {
      en: "Do you like it?",
      fr: "Aimez-vous ça?",
      es: "¿Te gusta?",
      de: "Magst du es?",
      hi: "क्या आपको यह पसंद है?",
    },
    "what is your favorite color": {
      en: "What is your favorite color?",
      fr: "Quelle est votre couleur préférée?",
      es: "¿Cuál es tu color favorito?",
      de: "Was ist deine Lieblingsfarbe?",
      hi: "आपका पसंदीदा रंग कौन सा है?",
    },
    "i understand": {
      en: "I understand",
      fr: "Je comprends",
      es: "Entiendo",
      de: "Ich verstehe",
      hi: "मैं समझ गया",
    },
    "do you have any questions": {
      en: "Do you have any questions?",
      fr: "Avez-vous des questions?",
      es: "¿Tienes alguna pregunta?",
      de: "Hast du Fragen?",
      hi: "क्या आपके पास कोई प्रश्न है?",
    },
    "this is my friend": {
      en: "This is my friend",
      fr: "C'est mon ami",
      es: "Este es mi amigo",
      de: "Das ist mein Freund",
      hi: "यह मेरा दोस्त है",
    },
    "i am a student": {
      en: "I am a student",
      fr: "Je suis étudiant",
      es: "Soy estudiante",
      de: "Ich bin Student",
      hi: "मैं एक छात्र हूँ",
    },
    "where is the nearest hotel": {
      en: "Where is the nearest hotel?",
      fr: "Où est l'hôtel le plus proche?",
      es: "¿Dónde está el hotel más cercano?",
      de: "Wo ist das nächste Hotel?",
      hi: "निकटतम होटल कहाँ है?",
    },
    "can i pay by card": {
      en: "Can I pay by card?",
      fr: "Puis-je payer par carte?",
      es: "¿Puedo pagar con tarjeta?",
      de: "Kann ich mit Karte bezahlen?",
      hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?",
    },
    "where are you going": {
      en: "Where are you going?",
      fr: "Où allez-vous?",
      es: "¿A dónde vas?",
      de: "Wohin gehst du?",
      hi: "आप कहाँ जा रहे हैं?",
    },
    "i am tired": {
      en: "I am tired",
      fr: "Je suis fatigué",
      es: "Estoy cansado",
      de: "Ich bin müde",
      hi: "मैं थक गया हूँ",
    },
    "can you repeat that": {
      en: "Can you repeat that?",
      fr: "Pouvez-vous répéter ça?",
      es: "¿Puedes repetir eso?",
      de: "Kannst du das wiederholen?",
      hi: "क्या आप इसे दोहरा सकते हैं?",
    },
    "i need directions": {
      en: "I need directions",
      fr: "J'ai besoin d'indications",
      es: "Necesito direcciones",
      de: "Ich brauche Wegbeschreibung",
      hi: "मुझे दिशा निर्देश चाहिए",
    },
    "how old are you": {
      en: "How old are you?",
      fr: "Quel âge avez-vous?",
      es: "¿Cuántos años tienes?",
      de: "Wie alt bist du?",
      hi: "आप कितने साल के हैं?",
    },
    "can you show me": {
      en: "Can you show me?",
      fr: "Pouvez-vous me montrer?",
      es: "¿Puedes mostrarme?",
      de: "Kannst du es mir zeigen?",
      hi: "क्या आप मुझे दिखा सकते हैं?",
    },
    "what are you doing": {
      en: "What are you doing?",
      fr: "Que faites-vous?",
      es: "¿Qué estás haciendo?",
      de: "Was machst du?",
      hi: "आप क्या कर रहे हैं?",
    },
    "i like this": {
      en: "I like this",
      fr: "J'aime ça",
      es: "Me gusta esto",
      de: "Ich mag das",
      hi: "मुझे यह पसंद है",
    },
    "where do you live": {
      en: "Where do you live?",
      fr: "Où habitez-vous?",
      es: "¿Dónde vives?",
      de: "Wo wohnst du?",
      hi: "आप कहाँ रहते हैं?",
    },
    "what is your hobby": {
      en: "What is your hobby?",
      fr: "Quel est votre passe-temps?",
      es: "¿Cuál es tu pasatiempo?",
      de: "Was ist dein Hobby?",
      hi: "आपका शौक क्या है?",
    },
    "i am hungry": {
      en: "I am hungry",
      fr: "J'ai faim",
      es: "Tengo hambre",
      de: "Ich habe Hunger",
      hi: "मुझे भूख लगी है",
    },
    "where is the supermarket": {
      en: "Where is the supermarket?",
      fr: "Où est le supermarché?",
      es: "¿Dónde está el supermercado?",
      de: "Wo ist der Supermarkt?",
      hi: "सुपरमार्केट कहाँ है?",
    },
    "can you call a taxi": {
      en: "Can you call a taxi?",
      fr: "Pouvez-vous appeler un taxi?",
      es: "¿Puedes llamar un taxi?",
      de: "Können Sie ein Taxi rufen?",
      hi: "क्या आप टैक्सी बुला सकते हैं?",
    },
    "i love this place": {
      en: "I love this place",
      fr: "J'adore cet endroit",
      es: "Me encanta este lugar",
      de: "Ich liebe diesen Ort",
      hi: "मुझे यह जगह पसंद है",
    },
    "do you have wifi": {
      en: "Do you have Wi-Fi?",
      fr: "Avez-vous le Wi-Fi?",
      es: "¿Tienes Wi-Fi?",
      de: "Haben Sie WLAN?",
      hi: "क्या आपके पास वाई-फाई है?",
    },
    "what time do you open": {
      en: "What time do you open?",
      fr: "À quelle heure ouvrez-vous?",
      es: "¿A qué hora abres?",
      de: "Wann öffnest du?",
      hi: "आप कितने बजे खोलते हैं?",
    },
    "do you take credit cards": {
      en: "Do you take credit cards?",
      fr: "Prenez-vous des cartes de crédit?",
      es: "¿Aceptas tarjetas de crédito?",
      de: "Nimmst du Kreditkarten?",
      hi: "क्या आप क्रेडिट कार्ड लेते हैं?",
    },
    "i am allergic to": {
      en: "I am allergic to",
      fr: "Je suis allergique à",
      es: "Soy alérgico a",
      de: "Ich bin allergisch gegen",
      hi: "मुझे इससे एलर्जी है",
    },
    "i am feeling sick": {
      en: "I am feeling sick",
      fr: "Je me sens malade",
      es: "Me siento enfermo",
      de: "Ich fühle mich krank",
      hi: "मैं बीमार महसूस कर रहा हूँ",
    },
    "can you speak slowly": {
      en: "Can you speak slowly?",
      fr: "Pouvez-vous parler lentement?",
      es: "¿Puedes hablar despacio?",
      de: "Kannst du langsam sprechen?",
      hi: "क्या आप धीरे से बोल सकते हैं?",
    },
    "can i sit here": {
      en: "Can I sit here?",
      fr: "Puis-je m'asseoir ici?",
      es: "¿Puedo sentarme aquí?",
      de: "Kann ich hier sitzen?",
      hi: "क्या मैं यहाँ बैठ सकता हूँ?",
    },
    "do you have change": {
      en: "Do you have change?",
      fr: "Avez-vous de la monnaie?",
      es: "¿Tienes cambio?",
      de: "Hast du Wechselgeld?",
      hi: "क्या आपके पास छुट्टे हैं?",
    },
    "can i get a menu": {
      en: "Can I get a menu?",
      fr: "Puis-je avoir un menu?",
      es: "¿Puedo ver el menú?",
      de: "Kann ich eine Speisekarte bekommen?",
      hi: "क्या मुझे मेनू मिल सकता है?",
    },
    "i like to travel": {
      en: "I like to travel",
      fr: "J'aime voyager",
      es: "Me gusta viajar",
      de: "Ich reise gern",
      hi: "मुझे यात्रा करना पसंद है",
    },
    "i am learning": {
      en: "I am learning",
      fr: "J'apprends",
      es: "Estoy aprendiendo",
      de: "Ich lerne",
      hi: "मैं सीख रहा हूँ",
    },
    "i am busy": {
      en: "I am busy",
      fr: "Je suis occupé",
      es: "Estoy ocupado",
      de: "Ich bin beschäftigt",
      hi: "मैं व्यस्त हूँ",
    },
    "i want to sleep": {
      en: "I want to sleep",
      fr: "Je veux dormir",
      es: "Quiero dormir",
      de: "Ich möchte schlafen",
      hi: "मुझे सोना है",
    },
    "let’s go": {
      en: "Let’s go",
      fr: "Allons-y",
      es: "Vámonos",
      de: "Lass uns gehen",
      hi: "चलो चलते हैं",
    },
    "what are you thinking": {
      en: "What are you thinking?",
      fr: "À quoi pensez-vous?",
      es: "¿En qué piensas?",
      de: "Woran denkst du?",
      hi: "आप क्या सोच रहे हैं?",
    },
    "how much do you earn": {
      en: "How much do you earn?",
      fr: "Combien gagnez-vous?",
      es: "¿Cuánto ganas?",
      de: "Wie viel verdienst du?",
      hi: "आप कितना कमाते हैं?",
    },
    "what is your favorite color": {
      en: "What is your favorite color?",
      fr: "Quelle est votre couleur préférée?",
      es: "¿Cuál es tu color favorito?",
      de: "Was ist deine Lieblingsfarbe?",
      hi: "आपका पसंदीदा रंग क्या है?",
    },
    "do you like music": {
      en: "Do you like music?",
      fr: "Aimez-vous la musique?",
      es: "¿Te gusta la música?",
      de: "Magst du Musik?",
      hi: "क्या आपको संगीत पसंद है?",
    },
    "i am happy": {
      en: "I am happy",
      fr: "Je suis heureux",
      es: "Estoy feliz",
      de: "Ich bin glücklich",
      hi: "मैं खुश हूँ",
    },
    "can i have a glass of water": {
      en: "Can I have a glass of water?",
      fr: "Puis-je avoir un verre d'eau?",
      es: "¿Puedo tener un vaso de agua?",
      de: "Kann ich ein Glas Wasser haben?",
      hi: "क्या मुझे एक गिलास पानी मिल सकता है?",
    },
    "i am coming": {
      en: "I am coming",
      fr: "J'arrive",
      es: "Ya voy",
      de: "Ich komme",
      hi: "मैं आ रहा हूँ",
    },
    "do you want to dance": {
      en: "Do you want to dance?",
      fr: "Voulez-vous danser?",
      es: "¿Quieres bailar?",
      de: "Möchtest du tanzen?",
      hi: "क्या आप नृत्य करना चाहते हैं?",
    },
    "please speak louder": {
      en: "Please speak louder",
      fr: "Veuillez parler plus fort",
      es: "Por favor, habla más alto",
      de: "Bitte sprich lauter",
      hi: "कृपया जोर से बोलें",
    },
    "i am in a meeting": {
      en: "I am in a meeting",
      fr: "Je suis en réunion",
      es: "Estoy en una reunión",
      de: "Ich bin in einer Besprechung",
      hi: "मैं एक बैठक में हूँ",
    },
    "let me know": {
      en: "Let me know",
      fr: "Faites-moi savoir",
      es: "Avísame",
      de: "Lass mich wissen",
      hi: "मुझे बताना",
    },
    "do you like sports": {
      en: "Do you like sports?",
      fr: "Aimez-vous le sport?",
      es: "¿Te gustan los deportes?",
      de: "Magst du Sport?",
      hi: "क्या आपको खेल पसंद है?",
    },
    "how do i get there": {
      en: "How do I get there?",
      fr: "Comment y arriver?",
      es: "¿Cómo llego allá?",
      de: "Wie komme ich dorthin?",
      hi: "वहाँ कैसे पहुँचूँ?",
    },
    "do you have a pen": {
      en: "Do you have a pen?",
      fr: "Avez-vous un stylo?",
      es: "¿Tienes un bolígrafo?",
      de: "Hast du einen Stift?",
      hi: "क्या आपके पास एक पेन है?",
    },
    "i need help": {
      en: "I need help",
      fr: "J'ai besoin d'aide",
      es: "Necesito ayuda",
      de: "Ich brauche Hilfe",
      hi: "मुझे मदद चाहिए",
    },
    "let’s meet tomorrow": {
      en: "Let’s meet tomorrow",
      fr: "Rencontrons-nous demain",
      es: "Nos vemos mañana",
      de: "Lass uns morgen treffen",
      hi: "आइए कल मिलते हैं",
    },
    "where is the exit": {
      en: "Where is the exit?",
      fr: "Où est la sortie?",
      es: "¿Dónde está la salida?",
      de: "Wo ist der Ausgang?",
      hi: "निकास कहाँ है?",
    },
    "do you understand english": {
      en: "Do you understand English?",
      fr: "Comprenez-vous l'anglais?",
      es: "¿Entiendes inglés?",
      de: "Verstehst du Englisch?",
      hi: "क्या आप अंग्रेजी समझते हैं?",
    },
    "i am lost": {
      en: "I am lost",
      fr: "Je suis perdu",
      es: "Estoy perdido",
      de: "Ich bin verloren",
      hi: "मैं खो गया हूँ",
    },
    "where can i find a taxi": {
      en: "Where can I find a taxi?",
      fr: "Où puis-je trouver un taxi?",
      es: "¿Dónde puedo encontrar un taxi?",
      de: "Wo finde ich ein Taxi?",
      hi: "मुझे टैक्सी कहाँ मिलेगी?",
    },
    "i don’t feel well": {
      en: "I don’t feel well",
      fr: "Je ne me sens pas bien",
      es: "No me siento bien",
      de: "Ich fühle mich nicht gut",
      hi: "मुझे अच्छा नहीं लग रहा है",
    },
    "can i borrow this": {
      en: "Can I borrow this?",
      fr: "Puis-je emprunter cela?",
      es: "¿Puedo tomar prestado esto?",
      de: "Kann ich das ausleihen?",
      hi: "क्या मैं इसे उधार ले सकता हूँ?",
    },
    "where is the nearest hospital": {
      en: "Where is the nearest hospital?",
      fr: "Où est l'hôpital le plus proche?",
      es: "¿Dónde está el hospital más cercano?",
      de: "Wo ist das nächste Krankenhaus?",
      hi: "निकटतम अस्पताल कहाँ है?",
    },
    "do you have a phone charger": {
      en: "Do you have a phone charger?",
      fr: "Avez-vous un chargeur de téléphone?",
      es: "¿Tienes un cargador de teléfono?",
      de: "Hast du ein Handy-Ladegerät?",
      hi: "क्या आपके पास फोन चार्जर है?",
    },
    "i am running late": {
      en: "I am running late",
      fr: "Je suis en retard",
      es: "Estoy llegando tarde",
      de: "Ich bin spät dran",
      hi: "मैं देर से आ रहा हूँ",
    },
    "where can i buy a ticket": {
      en: "Where can I buy a ticket?",
      fr: "Où puis-je acheter un billet?",
      es: "¿Dónde puedo comprar un boleto?",
      de: "Wo kann ich ein Ticket kaufen?",
      hi: "मैं टिकट कहाँ से खरीद सकता हूँ?",
    },
    "can you show me the way": {
      en: "Can you show me the way?",
      fr: "Pouvez-vous me montrer le chemin?",
      es: "¿Puedes mostrarme el camino?",
      de: "Kannst du mir den Weg zeigen?",
      hi: "क्या आप मुझे रास्ता दिखा सकते हैं?",
    },
    "how do i say this": {
      en: "How do I say this?",
      fr: "Comment dire cela?",
      es: "¿Cómo digo esto?",
      de: "Wie sage ich das?",
      hi: "मैं इसे कैसे कहूँ?",
    },
    "i need a doctor": {
      en: "I need a doctor",
      fr: "J'ai besoin d'un médecin",
      es: "Necesito un doctor",
      de: "Ich brauche einen Arzt",
      hi: "मुझे एक डॉक्टर चाहिए",
    },
    "please wait here": {
      en: "Please wait here",
      fr: "Veuillez attendre ici",
      es: "Por favor espera aquí",
      de: "Bitte warten Sie hier",
      hi: "कृपया यहाँ प्रतीक्षा करें",
    },
    "is there wifi here": {
      en: "Is there WiFi here?",
      fr: "Y a-t-il du WiFi ici?",
      es: "¿Hay WiFi aquí?",
      de: "Gibt es hier WLAN?",
      hi: "क्या यहाँ वाईफाई है?",
    },
    "what’s the address": {
      en: "What’s the address?",
      fr: "Quelle est l'adresse?",
      es: "¿Cuál es la dirección?",
      de: "Wie lautet die Adresse?",
      hi: "पता क्या है?",
    },
    "can you speak slowly": {
      en: "Can you speak slowly?",
      fr: "Pouvez-vous parler lentement?",
      es: "¿Puedes hablar despacio?",
      de: "Können Sie langsam sprechen?",
      hi: "क्या आप धीरे बोल सकते हैं?",
    },
    "i need some water": {
      en: "I need some water",
      fr: "J'ai besoin d'eau",
      es: "Necesito agua",
      de: "Ich brauche Wasser",
      hi: "मुझे कुछ पानी चाहिए",
    },
    "where is the train station": {
      en: "Where is the train station?",
      fr: "Où est la gare?",
      es: "¿Dónde está la estación de tren?",
      de: "Wo ist der Bahnhof?",
      hi: "रेलवे स्टेशन कहाँ है?",
    },
    "what’s the time now": {
      en: "What's the time now?",
      fr: "Quelle heure est-il?",
      es: "¿Qué hora es?",
      de: "Wie spät ist es?",
      hi: "अभी समय क्या हुआ है?",
    },
    "please call the police": {
      en: "Please call the police",
      fr: "Appelez la police, s'il vous plaît",
      es: "Por favor llame a la policía",
      de: "Bitte rufen Sie die Polizei",
      hi: "कृपया पुलिस को बुलाएं",
    },
    "i am looking for a hotel": {
      en: "I am looking for a hotel",
      fr: "Je cherche un hôtel",
      es: "Estoy buscando un hotel",
      de: "Ich suche ein Hotel",
      hi: "मैं एक होटल की तलाश कर रहा हूँ",
    },
    "can i see the menu": {
      en: "Can I see the menu?",
      fr: "Puis-je voir le menu?",
      es: "¿Puedo ver el menú?",
      de: "Kann ich die Speisekarte sehen?",
      hi: "क्या मैं मेनू देख सकता हूँ?",
    },
    "i am allergic to nuts": {
      en: "I am allergic to nuts",
      fr: "Je suis allergique aux noix",
      es: "Soy alérgico a los frutos secos",
      de: "Ich bin allergisch gegen Nüsse",
      hi: "मुझे नट्स से एलर्जी है",
    },
    "i would like to pay": {
      en: "I would like to pay",
      fr: "Je voudrais payer",
      es: "Me gustaría pagar",
      de: "Ich möchte bezahlen",
      hi: "मैं भुगतान करना चाहता हूँ",
    },
    "how far is the airport": {
      en: "How far is the airport?",
      fr: "À quelle distance est l'aéroport?",
      es: "¿A qué distancia está el aeropuerto?",
      de: "Wie weit ist der Flughafen?",
      hi: "हवाई अड्डा कितनी दूर है?",
    },
    "is breakfast included": {
      en: "Is breakfast included?",
      fr: "Le petit déjeuner est-il inclus?",
      es: "¿Está incluido el desayuno?",
      de: "Ist Frühstück inbegriffen?",
      hi: "क्या नाश्ता शामिल है?",
    },
    "i need a receipt": {
      en: "I need a receipt",
      fr: "J'ai besoin d'un reçu",
      es: "Necesito un recibo",
      de: "Ich brauche eine Quittung",
      hi: "मुझे रसीद चाहिए",
    },
    "how do i use the internet": {
      en: "How do I use the internet?",
      fr: "Comment utiliser Internet?",
      es: "¿Cómo uso Internet?",
      de: "Wie benutze ich das Internet?",
      hi: "मैं इंटरनेट कैसे उपयोग करूँ?",
    },
    "where can i buy groceries": {
      en: "Where can I buy groceries?",
      fr: "Où puis-je acheter de la nourriture?",
      es: "¿Dónde puedo comprar comestibles?",
      de: "Wo kann ich Lebensmittel kaufen?",
      hi: "मैं किराने का सामान कहाँ से खरीद सकता हूँ?",
    },
    "can i pay by card": {
      en: "Can I pay by card?",
      fr: "Puis-je payer par carte?",
      es: "¿Puedo pagar con tarjeta?",
      de: "Kann ich mit Karte zahlen?",
      hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?",
    },
    "do you have vegetarian food": {
      en: "Do you have vegetarian food?",
      fr: "Avez-vous de la nourriture végétarienne?",
      es: "¿Tienes comida vegetariana?",
      de: "Haben Sie vegetarisches Essen?",
      hi: "क्या आपके पास शाकाहारी भोजन है?",
    },
    "what time is check out": {
      en: "What time is check out?",
      fr: "À quelle heure est le départ?",
      es: "¿A qué hora es el check-out?",
      de: "Wann ist der Check-out?",
      hi: "चेक-आउट का समय क्या है?",
    },
    "i would like some coffee": {
      en: "I would like some coffee",
      fr: "Je voudrais du café",
      es: "Me gustaría un poco de café",
      de: "Ich hätte gerne Kaffee",
      hi: "मुझे कुछ कॉफी चाहिए",
    },
    "do you have any recommendations": {
      en: "Do you have any recommendations?",
      fr: "Avez-vous des recommandations?",
      es: "¿Tienes alguna recomendación?",
      de: "Haben Sie Empfehlungen?",
      hi: "क्या आपके पास कोई सिफारिश है?",
    },
    "how can i get a taxi": {
      en: "How can I get a taxi?",
      fr: "Comment puis-je obtenir un taxi?",
      es: "¿Cómo puedo conseguir un taxi?",
      de: "Wie bekomme ich ein Taxi?",
      hi: "मैं टैक्सी कैसे प्राप्त कर सकता हूँ?",
    },
    "do you have wifi": {
      en: "Do you have WiFi?",
      fr: "Avez-vous du WiFi?",
      es: "¿Tienes WiFi?",
      de: "Haben Sie WLAN?",
      hi: "क्या आपके पास वाईफाई है?",
    },
    "where can i find a pharmacy": {
      en: "Where can I find a pharmacy?",
      fr: "Où puis-je trouver une pharmacie?",
      es: "¿Dónde puedo encontrar una farmacia?",
      de: "Wo finde ich eine Apotheke?",
      hi: "मुझे एक फार्मेसी कहाँ मिलेगी?",
    },
    "can you show me the way": {
      en: "Can you show me the way?",
      fr: "Pouvez-vous me montrer le chemin?",
      es: "¿Puedes mostrarme el camino?",
      de: "Können Sie mir den Weg zeigen?",
      hi: "क्या आप मुझे रास्ता दिखा सकते हैं?",
    },
    "i would like a window seat": {
      en: "I would like a window seat",
      fr: "Je voudrais un siège près de la fenêtre",
      es: "Quisiera un asiento de ventana",
      de: "Ich möchte einen Fensterplatz",
      hi: "मुझे एक खिड़की वाली सीट चाहिए",
    },
    "where can i exchange money": {
      en: "Where can I exchange money?",
      fr: "Où puis-je échanger de l'argent?",
      es: "¿Dónde puedo cambiar dinero?",
      de: "Wo kann ich Geld wechseln?",
      hi: "मैं पैसे कहाँ बदल सकता हूँ?",
    },
    "is there a hospital nearby": {
      en: "Is there a hospital nearby?",
      fr: "Y a-t-il un hôpital à proximité?",
      es: "¿Hay un hospital cerca?",
      de: "Gibt es ein Krankenhaus in der Nähe?",
      hi: "क्या पास में कोई अस्पताल है?",
    },
    "can i have extra blankets": {
      en: "Can I have extra blankets?",
      fr: "Puis-je avoir des couvertures supplémentaires?",
      es: "¿Puedo tener mantas extra?",
      de: "Kann ich zusätzliche Decken haben?",
      hi: "क्या मुझे अतिरिक्त कंबल मिल सकते हैं?",
    },
    "i need a doctor": {
      en: "I need a doctor",
      fr: "J'ai besoin d'un médecin",
      es: "Necesito un doctor",
      de: "Ich brauche einen Arzt",
      hi: "मुझे एक डॉक्टर की जरूरत है",
    },
    "do you accept credit cards": {
      en: "Do you accept credit cards?",
      fr: "Acceptez-vous les cartes de crédit?",
      es: "¿Aceptan tarjetas de crédito?",
      de: "Akzeptieren Sie Kreditkarten?",
      hi: "क्या आप क्रेडिट कार्ड स्वीकार करते हैं?",
    },
    "where is the nearest atm": {
      en: "Where is the nearest ATM?",
      fr: "Où est le distributeur le plus proche?",
      es: "¿Dónde está el cajero automático más cercano?",
      de: "Wo ist der nächste Geldautomat?",
      hi: "निकटतम एटीएम कहाँ है?",
    },
    "i am feeling unwell": {
      en: "I am feeling unwell",
      fr: "Je ne me sens pas bien",
      es: "Me siento mal",
      de: "Ich fühle mich unwohl",
      hi: "मैं ठीक महसूस नहीं कर रहा हूँ",
    },
    "how long does it take": {
      en: "How long does it take?",
      fr: "Combien de temps cela prend-il?",
      es: "¿Cuánto tiempo tarda?",
      de: "Wie lange dauert es?",
      hi: "इसमें कितना समय लगेगा?",
    },
    "is there a parking area": {
      en: "Is there a parking area?",
      fr: "Y a-t-il un parking?",
      es: "¿Hay una zona de aparcamiento?",
      de: "Gibt es eine Parkzone?",
      hi: "क्या पार्किंग क्षेत्र है?",
    },
    "can i order room service": {
      en: "Can I order room service?",
      fr: "Puis-je commander un service de chambre?",
      es: "¿Puedo pedir servicio a la habitación?",
      de: "Kann ich Zimmerservice bestellen?",
      hi: "क्या मैं रूम सर्विस ऑर्डर कर सकता हूँ?",
    },
    "i am a vegetarian": {
      en: "I am a vegetarian",
      fr: "Je suis végétarien",
      es: "Soy vegetariano",
      de: "Ich bin Vegetarier",
      hi: "मैं शाकाहारी हूँ",
    },
    "i need help with my luggage": {
      en: "I need help with my luggage",
      fr: "J'ai besoin d'aide avec mes bagages",
      es: "Necesito ayuda con mi equipaje",
      de: "Ich brauche Hilfe mit meinem Gepäck",
      hi: "मुझे अपने सामान में मदद चाहिए",
    },
    "can you recommend a restaurant": {
      en: "Can you recommend a restaurant?",
      fr: "Pouvez-vous recommander un restaurant?",
      es: "¿Puedes recomendar un restaurante?",
      de: "Können Sie ein Restaurant empfehlen?",
      hi: "क्या आप किसी रेस्तरां की सिफारिश कर सकते हैं?",
    },
    "do you have a charger": {
      en: "Do you have a charger?",
      fr: "Avez-vous un chargeur?",
      es: "¿Tienes un cargador?",
      de: "Haben Sie ein Ladegerät?",
      hi: "क्या आपके पास चार्जर है?",
    },
    "can i get an early check-in": {
      en: "Can I get an early check-in?",
      fr: "Puis-je faire un enregistrement anticipé?",
      es: "¿Puedo hacer un check-in temprano?",
      de: "Kann ich früh einchecken?",
      hi: "क्या मुझे जल्दी चेक-इन मिल सकता है?",
    },
    "what are the local attractions": {
      en: "What are the local attractions?",
      fr: "Quelles sont les attractions locales?",
      es: "¿Cuáles son las atracciones locales?",
      de: "Was sind die lokalen Sehenswürdigkeiten?",
      hi: "स्थानीय आकर्षण क्या हैं?",
    },
    "do you have wifi": {
      en: "Do you have WiFi?",
      fr: "Avez-vous du WiFi?",
      es: "¿Tienes WiFi?",
      de: "Haben Sie WLAN?",
      hi: "क्या आपके पास वाईफाई है?",
    },
    "where can i find a pharmacy": {
      en: "Where can I find a pharmacy?",
      fr: "Où puis-je trouver une pharmacie?",
      es: "¿Dónde puedo encontrar una farmacia?",
      de: "Wo finde ich eine Apotheke?",
      hi: "मुझे एक फार्मेसी कहाँ मिलेगी?",
    },
    "can you show me the way": {
      en: "Can you show me the way?",
      fr: "Pouvez-vous me montrer le chemin?",
      es: "¿Puedes mostrarme el camino?",
      de: "Können Sie mir den Weg zeigen?",
      hi: "क्या आप मुझे रास्ता दिखा सकते हैं?",
    },
    "i would like a window seat": {
      en: "I would like a window seat",
      fr: "Je voudrais un siège près de la fenêtre",
      es: "Quisiera un asiento de ventana",
      de: "Ich möchte einen Fensterplatz",
      hi: "मुझे एक खिड़की वाली सीट चाहिए",
    },
    "where can i exchange money": {
      en: "Where can I exchange money?",
      fr: "Où puis-je échanger de l'argent?",
      es: "¿Dónde puedo cambiar dinero?",
      de: "Wo kann ich Geld wechseln?",
      hi: "मैं पैसे कहाँ बदल सकता हूँ?",
    },
    "is there a hospital nearby": {
      en: "Is there a hospital nearby?",
      fr: "Y a-t-il un hôpital à proximité?",
      es: "¿Hay un hospital cerca?",
      de: "Gibt es ein Krankenhaus in der Nähe?",
      hi: "क्या पास में कोई अस्पताल है?",
    },
    "can i have extra blankets": {
      en: "Can I have extra blankets?",
      fr: "Puis-je avoir des couvertures supplémentaires?",
      es: "¿Puedo tener mantas extra?",
      de: "Kann ich zusätzliche Decken haben?",
      hi: "क्या मुझे अतिरिक्त कंबल मिल सकते हैं?",
    },
    "i need a doctor": {
      en: "I need a doctor",
      fr: "J'ai besoin d'un médecin",
      es: "Necesito un doctor",
      de: "Ich brauche einen Arzt",
      hi: "मुझे एक डॉक्टर की जरूरत है",
    },
    "do you accept credit cards": {
      en: "Do you accept credit cards?",
      fr: "Acceptez-vous les cartes de crédit?",
      es: "¿Aceptan tarjetas de crédito?",
      de: "Akzeptieren Sie Kreditkarten?",
      hi: "क्या आप क्रेडिट कार्ड स्वीकार करते हैं?",
    },
    "where is the nearest atm": {
      en: "Where is the nearest ATM?",
      fr: "Où est le distributeur le plus proche?",
      es: "¿Dónde está el cajero automático más cercano?",
      de: "Wo ist der nächste Geldautomat?",
      hi: "निकटतम एटीएम कहाँ है?",
    },
    "i am feeling unwell": {
      en: "I am feeling unwell",
      fr: "Je ne me sens pas bien",
      es: "Me siento mal",
      de: "Ich fühle mich unwohl",
      hi: "मैं ठीक महसूस नहीं कर रहा हूँ",
    },
    "how long does it take": {
      en: "How long does it take?",
      fr: "Combien de temps cela prend-il?",
      es: "¿Cuánto tiempo tarda?",
      de: "Wie lange dauert es?",
      hi: "इसमें कितना समय लगेगा?",
    },
    "is there a parking area": {
      en: "Is there a parking area?",
      fr: "Y a-t-il un parking?",
      es: "¿Hay una zona de aparcamiento?",
      de: "Gibt es eine Parkzone?",
      hi: "क्या पार्किंग क्षेत्र है?",
    },
    "can i order room service": {
      en: "Can I order room service?",
      fr: "Puis-je commander un service de chambre?",
      es: "¿Puedo pedir servicio a la habitación?",
      de: "Kann ich Zimmerservice bestellen?",
      hi: "क्या मैं रूम सर्विस ऑर्डर कर सकता हूँ?",
    },
    "i am a vegetarian": {
      en: "I am a vegetarian",
      fr: "Je suis végétarien",
      es: "Soy vegetariano",
      de: "Ich bin Vegetarier",
      hi: "मैं शाकाहारी हूँ",
    },
    "i need help with my luggage": {
      en: "I need help with my luggage",
      fr: "J'ai besoin d'aide avec mes bagages",
      es: "Necesito ayuda con mi equipaje",
      de: "Ich brauche Hilfe mit meinem Gepäck",
      hi: "मुझे अपने सामान में मदद चाहिए",
    },
    "can you recommend a restaurant": {
      en: "Can you recommend a restaurant?",
      fr: "Pouvez-vous recommander un restaurant?",
      es: "¿Puedes recomendar un restaurante?",
      de: "Können Sie ein Restaurant empfehlen?",
      hi: "क्या आप किसी रेस्तरां की सिफारिश कर सकते हैं?",
    },
    "do you have a charger": {
      en: "Do you have a charger?",
      fr: "Avez-vous un chargeur?",
      es: "¿Tienes un cargador?",
      de: "Haben Sie ein Ladegerät?",
      hi: "क्या आपके पास चार्जर है?",
    },
    "can i get an early check-in": {
      en: "Can I get an early check-in?",
      fr: "Puis-je faire un enregistrement anticipé?",
      es: "¿Puedo hacer un check-in temprano?",
      de: "Kann ich früh einchecken?",
      hi: "क्या मुझे जल्दी चेक-इन मिल सकता है?",
    },
    "what are the local attractions": {
      en: "What are the local attractions?",
      fr: "Quelles sont les attractions locales?",
      es: "¿Cuáles son las atracciones locales?",
      de: "Was sind die lokalen Sehenswürdigkeiten?",
      hi: "स्थानीय आकर्षण क्या हैं?",
    },
    "do you have wifi": {
      en: "Do you have WiFi?",
      fr: "Avez-vous du WiFi?",
      es: "¿Tienes WiFi?",
      de: "Haben Sie WLAN?",
      hi: "क्या आपके पास वाईफाई है?",
    },
    "where can i find a pharmacy": {
      en: "Where can I find a pharmacy?",
      fr: "Où puis-je trouver une pharmacie?",
      es: "¿Dónde puedo encontrar una farmacia?",
      de: "Wo finde ich eine Apotheke?",
      hi: "मुझे एक फार्मेसी कहाँ मिलेगी?",
    },
    "can you show me the way": {
      en: "Can you show me the way?",
      fr: "Pouvez-vous me montrer le chemin?",
      es: "¿Puedes mostrarme el camino?",
      de: "Können Sie mir den Weg zeigen?",
      hi: "क्या आप मुझे रास्ता दिखा सकते हैं?",
    },
    "i would like a window seat": {
      en: "I would like a window seat",
      fr: "Je voudrais un siège près de la fenêtre",
      es: "Quisiera un asiento de ventana",
      de: "Ich möchte einen Fensterplatz",
      hi: "मुझे एक खिड़की वाली सीट चाहिए",
    },
    "where can i exchange money": {
      en: "Where can I exchange money?",
      fr: "Où puis-je échanger de l'argent?",
      es: "¿Dónde puedo cambiar dinero?",
      de: "Wo kann ich Geld wechseln?",
      hi: "मैं पैसे कहाँ बदल सकता हूँ?",
    },
    "is there a hospital nearby": {
      en: "Is there a hospital nearby?",
      fr: "Y a-t-il un hôpital à proximité?",
      es: "¿Hay un hospital cerca?",
      de: "Gibt es ein Krankenhaus in der Nähe?",
      hi: "क्या पास में कोई अस्पताल है?",
    },
    "can i have extra blankets": {
      en: "Can I have extra blankets?",
      fr: "Puis-je avoir des couvertures supplémentaires?",
      es: "¿Puedo tener mantas extra?",
      de: "Kann ich zusätzliche Decken haben?",
      hi: "क्या मुझे अतिरिक्त कंबल मिल सकते हैं?",
    },
    "i need a doctor": {
      en: "I need a doctor",
      fr: "J'ai besoin d'un médecin",
      es: "Necesito un doctor",
      de: "Ich brauche einen Arzt",
      hi: "मुझे एक डॉक्टर की जरूरत है",
    },
    "do you accept credit cards": {
      en: "Do you accept credit cards?",
      fr: "Acceptez-vous les cartes de crédit?",
      es: "¿Aceptan tarjetas de crédito?",
      de: "Akzeptieren Sie Kreditkarten?",
      hi: "क्या आप क्रेडिट कार्ड स्वीकार करते हैं?",
    },
    "where is the nearest atm": {
      en: "Where is the nearest ATM?",
      fr: "Où est le distributeur le plus proche?",
      es: "¿Dónde está el cajero automático más cercano?",
      de: "Wo ist der nächste Geldautomat?",
      hi: "निकटतम एटीएम कहाँ है?",
    },
    "i am feeling unwell": {
      en: "I am feeling unwell",
      fr: "Je ne me sens pas bien",
      es: "Me siento mal",
      de: "Ich fühle mich unwohl",
      hi: "मैं ठीक महसूस नहीं कर रहा हूँ",
    },
    "how long does it take": {
      en: "How long does it take?",
      fr: "Combien de temps cela prend-il?",
      es: "¿Cuánto tiempo tarda?",
      de: "Wie lange dauert es?",
      hi: "इसमें कितना समय लगेगा?",
    },
    "is there a parking area": {
      en: "Is there a parking area?",
      fr: "Y a-t-il un parking?",
      es: "¿Hay una zona de aparcamiento?",
      de: "Gibt es eine Parkzone?",
      hi: "क्या पार्किंग क्षेत्र है?",
    },
    "can i order room service": {
      en: "Can I order room service?",
      fr: "Puis-je commander un service de chambre?",
      es: "¿Puedo pedir servicio a la habitación?",
      de: "Kann ich Zimmerservice bestellen?",
      hi: "क्या मैं रूम सर्विस ऑर्डर कर सकता हूँ?",
    },
    "i am a vegetarian": {
      en: "I am a vegetarian",
      fr: "Je suis végétarien",
      es: "Soy vegetariano",
      de: "Ich bin Vegetarier",
      hi: "मैं शाकाहारी हूँ",
    },
    "i need help with my luggage": {
      en: "I need help with my luggage",
      fr: "J'ai besoin d'aide avec mes bagages",
      es: "Necesito ayuda con mi equipaje",
      de: "Ich brauche Hilfe mit meinem Gepäck",
      hi: "मुझे अपने सामान में मदद चाहिए",
    },
    "can you recommend a restaurant": {
      en: "Can you recommend a restaurant?",
      fr: "Pouvez-vous recommander un restaurant?",
      es: "¿Puedes recomendar un restaurante?",
      de: "Können Sie ein Restaurant empfehlen?",
      hi: "क्या आप किसी रेस्तरां की सिफारिश कर सकते हैं?",
    },
    "do you have a charger": {
      en: "Do you have a charger?",
      fr: "Avez-vous un chargeur?",
      es: "¿Tienes un cargador?",
      de: "Haben Sie ein Ladegerät?",
      hi: "क्या आपके पास चार्जर है?",
    },
    "can i get an early check-in": {
      en: "Can I get an early check-in?",
      fr: "Puis-je faire un enregistrement anticipé?",
      es: "¿Puedo hacer un check-in temprano?",
      de: "Kann ich früh einchecken?",
      hi: "क्या मुझे जल्दी चेक-इन मिल सकता है?",
    },
    "what are the local attractions": {
      en: "What are the local attractions?",
      fr: "Quelles sont les attractions locales?",
      es: "¿Cuáles son las atracciones locales?",
      de: "Was sind die lokalen Sehenswürdigkeiten?",
      hi: "स्थानीय आकर्षण क्या हैं?",
    },
  };

  // Helper function to find the input phrase in any language
  function findTranslation(input, fromLang, toLang) {
    for (let phrase in translations) {
      if (
        translations[phrase][fromLang] &&
        translations[phrase][fromLang].toLowerCase() === input
      ) {
        return translations[phrase][toLang] || "Translation not available";
      }
    }
    return "Translation not available";
  }

  // Translate from any language to any other language
  translatedText = findTranslation(inputText, fromLang, toLang);

  document.getElementById("output-text").value = translatedText;
}

// Show modal for mic button
function showModal() {
  const modal = document.getElementById("voiceModal");
  modal.style.display = "block";
}

// Close modal
function closeModal() {
  const modal = document.getElementById("voiceModal");
  modal.style.display = "none";
}

// Simulate speak output
function speakOutput() {
  alert("Voice output activated!");
}
